import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark` }
      >
        {/* Sticky header */}
        <div className="sticky top-0 left-0 w-full z-50 overflow-hidden bg-background shadow-md">
          <Header />
        </div>

        {/* Page content */}
        <main>
          {children}
        </main>

        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
